server:
  port: 8080

spring:
  application:
    name: course-search-app

  # Elasticsearch config
  elasticsearch:
    uris: http://localhost:9200

  # MySQL config (optional; not used in this project)
  datasource:
    url: jdbc:mysql://localhost:3306/courses_db/createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
