server:
  port: 8080

spring:
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 10s

  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:mysql://localhost:3306/courses_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web: DEBUG
    com.undoschool.course_search: DEBUG
